name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write   # 👈 allow the bot to push changes

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TryHackMe Badge Workflow
        uses: p4p1/tryhackme-badge-workflow@1.0.0
        with:
          username: "myokohi"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
